const SHOW_ALL_USERS = "SHOW_ALL_USERS";
const SHOW_ALL_USERS_FAILED = "SHOW_ALL_USERS_FAILED";
const EDIT_USER = "EDIT_USER";
const EDIT_USER_FAILED = "EDIT_USER_FAILED";
const DELETE_USER = "DELETE_USER";
const USER_EDIT_SUBMITTED = "USER_EDIT_SUBMITTED";
const USER_EDIT_SUBMITTED_FAILED = "USER_EDIT_SUBMITTED_FAILED";

export {
  SHOW_ALL_USERS,
  SHOW_ALL_USERS_FAILED,
  EDIT_USER,
  EDIT_USER_FAILED,
  DELETE_USER,
  USER_EDIT_SUBMITTED,
  USER_EDIT_SUBMITTED_FAILED
};
